#! /usr/bin/env python2
from PyQt4.QtGui import QApplication
from visigoth import remote


if __name__ == "__main__":

    app = QApplication([])
    win = remote.RemoteApp()
    win.show()
    app.exec_()
