#! /usr/bin/env python2
import time
import json
import socket
import Queue as queue

from PyQt4.QtGui import QApplication

from visigoth import remote, clientserver


if __name__ == "__main__":

    """
    trial_q = queue.Queue()
    param_q = queue.Queue()
    screen_q = queue.Queue()

    for _ in xrange(10):
        try:
            client = clientserver.SocketClientThread(screen_q,
                                                     param_q,
                                                     trial_q)
            client.start()
            print "Connected"
            break
        except socket.error:
            print "Failed to connect"
            time.sleep(1)

    while True:

        try:
            screen = screen_q.get(timeout=.01)
            print("Screen data:", screen)
        except queue.Empty:
            pass
    """

    app = QApplication([])
    win = remote.RemoteApp()
    win.show()
    app.exec_()
