#! /usr/bin/env python2
import os
import sys
from visigoth.experiment import Experiment


if __name__ == "__main__":

    sys.path.insert(0, os.path.realpath("."))

    import experiment

    Experiment.create_stimuli = experiment.create_stimuli
    Experiment.generate_trials = experiment.generate_trials
    Experiment.run_trial = experiment.run_trial
    if hasattr(experiment, "define_cmdline_params"):
        Experiment.define_cmdline_params = experiment.define_cmdline_params
    if hasattr(experiment, "update_client"):
        Experiment.update_client = experiment.update_client
    if hasattr(experiment, "save_data"):
        Experiment.save_data = experiment.save_data

    Experiment(sys.argv[1:]).run()
